/* ------------------------------------------------------------------ */
/*  Blog post index — verbatim from https://renoregen.com/blog/       */
/*  Order matches the live site (most recent first).                  */
/* ------------------------------------------------------------------ */

export type Post = {
  slug: string;
  title: string;
  date: string;
  image: string;
  excerpt: string;
  category: string;
  /** Compiled posts live at /{slug}/. Ranked posts live at /blog/{slug}/. */
  href?: string;
};

export const POSTS: readonly Post[] = [
  { slug: "reno-stem-cell-therapy-costs-safety-and-clinic-tips", title: "Reno Stem Cell Therapy Costs, Safety, And Clinic Tips", date: "September 21, 2026", image: "/blogs-images/reno-stem-cell-therapy-costs-safety-and-clinic-tips.png", excerpt: "Use this patient checklist to compare stem cell therapy in Reno, understand costs and safety, and spot red flags before choosing a clinic", category: "regenerative-medicine" },
  { slug: "stem-cell-prp-or-exosomes-in-reno-how-to-choose", title: "Stem Cell, PRP, Or Exosomes in Reno: How to Choose", date: "September 17, 2026", image: "/blogs-images/stem-cell-prp-or-exosomes-in-reno-how-to-choose.png", excerpt: "Compare stem cell therapy in Reno with PRP and exosomes. Learn what is legal, what evidence supports, and how to pick the right option for pain relief", category: "regenerative-medicine" },
  { slug: "living-with-arthritis-in-renos-climate-when-to-seek-treatment", title: "Living with Arthritis in Reno’s Climate: When to Seek Treatment", date: "September 10, 2026", image: "/images/blogs-images/unique-living-with-arthritis-in-renos-climate-when-to-seek-treatment.jpg", excerpt: "Reno’s dry air, altitude, and big temperature swings can make arthritis pain louder. Learn how the local climate affects your joints and when it is time to look into arthritis treatment in Reno.", category: "regenerative-medicine" },
  { slug: "inside-integrative-medicine-in-reno-a-patients-first-90-days", title: "Inside Integrative Medicine in Reno: A Patient’s First 90 Days", date: "September 3, 2026", image: "/new-blogs-images/inside-integrative-medicine-in-reno-a-patients-first-90-days.jpg", excerpt: "Curious what integrative care actually looks like week to week? Follow a typical new-patient journey through evaluation, treatment, and progress checks over 90 days.", category: "integrative-medicine" },
  { slug: "your-first-90-days-of-integrative-care-in-reno", title: "Your First 90 Days of Integrative Care in Reno", date: "August 27, 2026", image: "/blogs-images/your-first-90-days-of-integrative-care-in-reno.webp", excerpt: "Explore what to expect from integrative medicine in Reno during your first 90 days, from evaluation to personalized therapies for pain relief and mobility.", category: "integrative-medicine" },
  { slug: "regenerative-medicine-or-decompression-for-back-pain", title: "Regenerative Medicine vs. Spinal Decompression in Reno: Who Benefits?", date: "August 20, 2026", image: "/images/blogs-images/regenerative-medicine-or-decompression-for-back-pain.jpg", excerpt: "Compare treatment options for chronic back pain and see who benefits most from regenerative medicine in Reno, plus spinal decompression and integrative care.", category: "spinal-decompression" },
  { slug: "reno-commute-and-workstation-fixes-ergonomic-tweaks-for-faster-back-pain-relief", title: "Reno Ergonomic Commute Tips for Faster Back Pain Relief", date: "August 13, 2026", image: "/images/blogs-images/reno-ergonomic-commute-tips-for-faster-back-pain-relief.png", excerpt: "Learn how small commute and workstation changes can boost back pain treatment in Reno, easing strain and supporting quicker recovery at work and home.", category: "chiropractic-care" },
  { slug: "why-hormone-therapy-in-reno-nv-matters-for-joint-pain-relief", title: "Why Hormone Therapy in Reno NV Matters for Joint Pain Relief", date: "August 6, 2026", image: "/images/blogs-images/unique-why-hormone-therapy-in-reno-nv-matters-for-joint-pain-relief.jpg", excerpt: "Joint pain is not always just wear and tear. See how shifting hormone levels can drive inflammation and slower recovery, and why balanced hormones matter for lasting joint comfort.", category: "hormone-therapy" },
  { slug: "hormone-therapy-options-for-joint-pain-in-reno-nv", title: "Hormone Therapy Options for Joint Pain in Reno, NV", date: "July 30, 2026", image: "/images/blogs-images/hormone-therapy-options-for-joint-pain-in-reno-nv.jpg", excerpt: "Joint pain may not be just wear and tear. Learn how hormone therapy in Reno, NV can reduce inflammation, protect cartilage, and support integrative joint healing for lasting relief.", category: "hormone-therapy" },
  { slug: "signs-joint-pain-may-need-regenerative-treatment", title: "Everyday Clues Your Joint Pain Needs Regenerative Medicine", date: "July 23, 2026", image: "/images/blogs-images/signs-joint-pain-may-need-regenerative-treatment.png", excerpt: "Joint pain does not show up out of nowhere. Learn the everyday clues, from morning stiffness to pain that outlasts activity, that may mean it is time to explore regenerative medicine in Reno.", category: "regenerative-medicine" },
  { slug: "when-knee-pain-signals-a-need-for-expert-care-in-reno", title: "Local Clues Your Knee Pain Needs a Reno Pain Management Clinic Visit", date: "July 16, 2026", image: "/images/blogs-images/when-knee-pain-signals-a-need-for-expert-care-in-reno.jpeg", excerpt: "Knee pain that changes how you move through everyday Reno life is a signal worth taking seriously. Learn the local clues that mean it is time to see a pain management clinic in Reno.", category: "knee-decompression" },
  { slug: "common-shoulder-pain-triggers-for-active-adults-in-reno", title: "Reno\u2019s Hidden Causes of Shoulder Pain That Active Adults Overlook", date: "July 9, 2026", image: "/images/blogs-images/common-shoulder-pain-triggers-for-active-adults-in-reno.jpg", excerpt: "Shoulder pain that keeps coming back rarely starts with one big injury. Discover the hidden causes active Reno adults overlook and when to see a shoulder pain doctor in Reno for non-surgical, integrative care.", category: "joint-injections" },
  { slug: "integrative-medicine-solutions-for-pain-relief-in-reno", title: "Beyond Pain Pills: Integrative Medicine Options in Reno", date: "July 2, 2026", image: "/images/blogs-images/integrative-medicine-solutions-for-pain-relief-in-reno.jpeg", excerpt: "Pain pills mask symptoms but rarely fix the source. See how integrative medicine in Reno blends chiropractic care, regenerative injections, IV therapy, and hormone support to help you move more and hurt less.", category: "integrative-medicine" },
  { slug: "persistent-shoulder-pain-may-start-in-your-spine", title: "What Persistent Shoulder Pain Reveals About Your Spine", date: "June 25, 2026", image: "/images/blogs-images/persistent-shoulder-pain-may-start-in-your-spine.webp", excerpt: "A lot of long-lasting shoulder pain actually starts in the neck and upper back. Learn how spine issues drive shoulder symptoms and when to see a shoulder pain doctor in Reno for integrative, non-surgical care.", category: "chiropractic-care" },
  { slug: "reno-road-trip-knee-pain-when-to-see-a-doctor", title: "Summer Joint Pain Road Trips in Reno: When to See a Doctor", date: "June 18, 2026", image: "/images/blogs-images/reno-road-trip-knee-pain-when-to-see-a-doctor.jpeg", excerpt: "Long summer drives around northern Nevada should feel fun, not painful. Learn when road trip knee pain warrants seeing a knee pain doctor in Reno and how integrative care can help you keep exploring.", category: "knee-decompression" },
  { slug: "summer-sports-back-pain-relief-tips-for-nevada-athletes", title: "Nevada Athletes and Back Pain Treatment for Summer Sports", date: "June 11, 2026", image: "/images/blogs-images/summer-sports-back-pain-relief-tips-for-nevada-athletes.webp", excerpt: "Back pain can turn a fun summer season into weeks on the sidelines. See how non-surgical back pain treatment in Reno helps Nevada athletes stay strong through softball, hiking, tennis, and mountain biking.", category: "chiropractic-care" },
  { slug: "signs-of-hormone-imbalance-vs-normal-aging-in-reno", title: "Hormone Imbalance or Just Aging? How Reno Patients Can Tell", date: "June 4, 2026", image: "/images/blogs-images/signs-of-hormone-imbalance-vs-normal-aging-in-reno.jpeg", excerpt: "Feeling wiped out is not just something you have to accept with age. Learn how to tell hormone imbalance apart from normal aging and when hormone therapy in Reno may help you feel like yourself again.", category: "hormone-therapy" },
  { slug: "boost-energy-and-recovery-with-iv-therapy-in-reno", title: "Recharging Active Summers with Nutritional IV Therapy in Reno", date: "May 28, 2026", image: "/images/blogs-images/boost-energy-and-recovery-with-iv-therapy-in-reno.jpg", excerpt: "Active summers in Reno can drain you faster than expected. See how nutritional IV therapy in Reno supports hydration, energy, and recovery for weekend warriors, athletes, and busy professionals.", category: "nutritional-ivs" },
  { slug: "choosing-between-joint-injections-and-spinal-decompression-in-reno", title: "Choosing Between Joint Injections and Spinal Decompression in Reno", date: "May 21, 2026", image: "/new-blogs-images/choosing-between-joint-injections-and-spinal-decompression-in-reno.jpeg", excerpt: "Not sure whether joint injections or spinal decompression fit your pain better? Compare how each nonsurgical option works and who tends to benefit most from each.", category: "joint-injections" },
  { slug: "chiropractic-care-active-weekends-mountain-adventures", title: "Chiropractic Care for Active Reno Weekends and Mountain Adventures", date: "May 14, 2026", image: "/new-blogs-images/chiropractic-care-for-active-reno-weekends-and-mountain-adventures.webp", excerpt: "Move Better, Play Harder in Reno\u2019s Great Outdoors. Reno weekends are made for movement \u2014 river walks along the Truckee, laps up Peavine, hikes in the Sierra, paddling at Tahoe. Chiropractic care keeps weekend warriors aligned, mobile, and ready to recover.", category: "chiropractic-care" },
  { slug: "planning-a-summer-hiking-season-with-chronic-knee-pain", title: "Planning a Summer Hiking Season with Chronic Knee Pain", date: "May 7, 2026", image: "/new-blogs-images/planning-a-summer-hiking-season-with-chronic-knee-pain.jpg", excerpt: "Chronic knee pain does not have to keep you off Reno’s summer trails. Get a simple plan for training, trail selection, and pacing so you can hike with more confidence.", category: "knee-decompression" },
  { slug: "habits-that-quietly-worsen-knee-pain", title: "Everyday Habits That Quietly Worsen Knee Pain in Reno", date: "April 30, 2026", image: "/images/blogs-images/unique-habits-that-quietly-worsen-knee-pain.jpg", excerpt: "Simple Daily Choices That Make Knee Pain Worse Knee pain rarely shows up out of nowhere. For many people in Reno, it builds slowly over", category: "knee-decompression" },
  { slug: "backpackers-guide-sciatica-treatment-options", title: "Backpackers\u2019 Guide to Sciatica Treatment Options in Reno", date: "April 23, 2026", image: "/new-blogs-images/backpackers-guide-to-sciatica-treatment-options-in-reno.jpeg", excerpt: "Hit the Trail Without Sciatica Holding You Back Sciatica can turn a dream backpacking trip into a long, painful slog. If you hike with a", category: "spinal-decompression" },
  { slug: "life-after-whiplash-when-seek-care", title: "Life After Whiplash: When to Seek Integrative Pain Care", date: "April 16, 2026", image: "/images/blogs-images/unique-life-after-whiplash-when-seek-care.jpg", excerpt: "Whiplash can turn a small car accident into a big problem for your daily life. A simple rear-end tap on I-80 or a slow roll", category: "chiropractic-care" },
  { slug: "regenerative-medicine-for-chronic-back-pain", title: "Understanding Regenerative Medicine for Chronic Back Pain", date: "April 9, 2026", image: "/new-blogs-images/understanding-regenerative-medicine-for-chronic-back-pain.jpg", excerpt: "Break Free From Chronic Back Pain This Spring Chronic back pain can touch every part of your day. It can make work harder, shorten family", category: "regenerative-medicine" },
  { slug: "is-regenerative-medicine-right-for-knee-pain", title: "Is Regenerative Medicine Right for Your Knee Pain?", date: "April 2, 2026", image: "/images/blogs-images/unique-is-regenerative-medicine-right-for-knee-pain.jpg", excerpt: "Stop Letting Knee Pain Dictate Your Spring Plans Knee pain has a way of stealing the things you look forward to most. Walking local trails,", category: "regenerative-medicine" },
  { slug: "signs-back-pain-needs-spinal-decompression", title: "Warning Signs Your Back Pain Needs Spinal Decompression", date: "March 26, 2026", image: "/new-blogs-images/warning-signs-your-back-pain-needs-sp-needs-spinal-decompression.jpg", excerpt: "When Back Pain Becomes More Than Just Sore Muscles Back stiffness after a long day outside, cleaning the garage, or catching up on yard work", category: "spinal-decompression" },
  { slug: "why-your-knees-hurt-more-when-going-down-stairs-what-it-means-for-your-joint-health", title: "Why Your Knees Hurt More When Going Down Stairs: What It Means for Your Joint Health", date: "March 19, 2026", image: "/images/blogs-images/unique-why-your-knees-hurt-more-when-going-down-stairs-what-it-means-for-your-joint-health.jpg", excerpt: "Discover why your knees hurt when going down stairs and how knee decompression therapy in Reno can relieve pressure and restore joint function.", category: "knee-decompression" },
  { slug: "why-your-joints-feel-stiff-every-morning-what-your-body-is-trying-to-tell-you", title: "Why Your Joints Feel Stiff Every Morning: What Your Body Is Trying to Tell You", date: "March 12, 2026", image: "/new-blogs-images/why-your-joints-feel-stiff-every-morning-what-your-body-is-trying-to-tell-you.webp", excerpt: "Discover why your joints feel stiff every morning and how regenerative medicine and joint injections in Reno can restore mobility.", category: "joint-injections" },
  { slug: "mood-swings-anxiety-irritability-when-hormones-not-stress-are-the-real-problem", title: "Mood Swings, Anxiety & Irritability: When Hormones \u2014 Not Stress \u2014 Are the Real Problem", date: "March 5, 2026", image: "/images/blogs-images/unique-mood-swings-anxiety-irritability-when-hormones-not-stress-are-the-real-problem.jpg", excerpt: "Discover how bioidentical hormone optimization in Reno can stabilize mood swings, reduce anxiety, and restore emotional balance.", category: "hormone-therapy" },
  { slug: "why-youre-still-exhausted-after-8-hours-of-sleep-the-hidden-hormone-imbalance-most-people-miss", title: "Why You\u2019re Still Exhausted After 8 Hours of Sleep: The Hidden Hormone Imbalance Most People Miss", date: "February 26, 2026", image: "/images/blogs-images/unique-why-youre-still-exhausted-after-8-hours-of-sleep-the-hidden-hormone-imbalance-most-people-miss.jpg", excerpt: "Discover how bioidentical hormone therapy in Reno can correct hormone imbalance and restore energy, focus, and vitality.", category: "hormone-therapy" },
  { slug: "the-knee-that-locks-up-why-it-happens-and-how-knee-decompression-can-free-your-movement", title: "The Knee That \u201cLocks Up\u201d: Why It Happens and How Knee Decompression Can Free Your Movement", date: "February 19, 2026", image: "/new-blogs-images/the-knee-that-locks-up-why-it-happens-and-how-knee-decompression-can-free-you.jpeg", excerpt: "Learn why your knee locks or stiffens and how non-surgical knee decompression in Reno can restore smooth, confident movement.", category: "knee-decompression" },
  { slug: "why-your-knee-feels-like-its-grinding-how-knee-decompression-can-ease-annoying-joint-catching", title: "Why Your Knee Feels Like It\u2019s Grinding: How Knee Decompression Can Ease Annoying Joint Catching", date: "February 12, 2026", image: "/new-blogs-images/why-your-knee-feels-like-its-grinding-how-knee-decompression-can-ease-it.jpeg", excerpt: "Learn why your knee feels like it\u2019s grinding or catching and how knee decompression therapy in Reno can help relieve joint pressure.", category: "knee-decompression" },
  { slug: "struggling-with-dizziness-or-vertigo-physical-therapy-can-help-you-steady-yourself-in-reno", title: "Struggling With Dizziness or Vertigo? Physical Therapy Can Help You Steady Yourself in Reno", date: "February 5, 2026", image: "/new-blogs-images/struggling-with-dizziness-or-vertigo-physical-therapy-can-help-you-steady-yourself-in-reno.jpg", excerpt: "Learn how vestibular physical therapy in Reno helps relieve dizziness, vertigo, and balance problems for safer, steadier movement.", category: "physical-therapy" },
  { slug: "after-the-fall-how-physical-therapy-in-reno-can-get-you-back-on-your-feet-safely", title: "After the Fall: How Physical Therapy in Reno Can Get You Back on Your Feet Safely", date: "January 29, 2026", image: "/new-blogs-images/after-the-fall-how-physical-therapy-in-reno-can-get-you-back-on-your-feet-safely.webp", excerpt: "Learn how physical therapy in Reno helps you recover after a fall, restore mobility, and regain confidence in your balance.", category: "physical-therapy" },
  { slug: "recovering-from-surgery-why-post-operative-physical-therapy-is-the-key-to-faster-safer-healing", title: "Recovering From Surgery? Why Post-Operative Physical Therapy in Reno Is the Key to Faster, Safer Healing", date: "January 22, 2026", image: "/new-blogs-images/recovering-from-surgery-why-post-operative-physical-therapy-in-reno-is-the-key-to-faster-safer-healing.jpeg", excerpt: "When you\u2019re recovering from surgery, each day can feel like a mix of hope, frustration, progress, and setback. Your body is healing, yet simple movements", category: "physical-therapy" },
  { slug: "from-stiff-to-strong-how-physical-therapy-in-reno-can-restore-your-mobility-after-years-of-joint-pain", title: "From Stiff to Strong: How Physical Therapy in Reno Can Restore Your Mobility After Years of Joint Pain", date: "January 15, 2026", image: "/images/blogs-images/unique-from-stiff-to-strong-how-physical-therapy-in-reno-can-restore-your-mobility-after-years-of-joint-pain.jpg", excerpt: "If you\u2019ve been living with stiffness or joint pain for months\u2014or even years\u2014you may have started to believe that this is simply the way your", category: "physical-therapy" },
  { slug: "knot-your-average-pain-how-trigger-point-injections-can-relieve-chronic-muscle-tension", title: "Knot Your Average Pain: How Trigger Point Injections in Reno Can Relieve Chronic Muscle Tension", date: "January 8, 2026", image: "/new-blogs-images/knot-your-average-pain-how-trigger-point-injections-in-reno-can-relieve-chronic-muscle.webp", excerpt: "Do you ever feel like your body is one big knot? Your shoulders ache by midday, your neck feels stiff after working at your desk,", category: "trigger-point-injections" },
  { slug: "balancing-act-how-bioidentical-hormone-therapy-can-restore-your-vitality-and-well-being", title: "Balancing Act: How Bioidentical Hormone Therapy in Reno Can Restore Your Vitality and Well-being", date: "January 1, 2026", image: "/new-blogs-images/balancing-act-how-bioidentical-hormone-therapy-in-reno-can-restore-your-vitality-and-well-being.jpeg", excerpt: "Do you ever feel like your body is working against you? You wake up exhausted, even after a full night of sleep, or find yourself", category: "hormone-therapy" },
  { slug: "reclaim-your-life-with-non-surgical-joint-injections-in-reno", title: "Reclaim Your Life with Non-Surgical Joint Injections in Reno", date: "December 25, 2025", image: "/new-blogs-images/reclaim-your-life-with-non-surgical-joint-injections-in-reno.jpeg", excerpt: "Discover how non-surgical joint injections in Reno can relieve chronic joint pain, improve mobility, and help you regain an active, pain-free lifestyle", category: "joint-injections" },
  { slug: "how-nutritional-iv-therapy-can-combat-stress-fatigue", title: "How Nutritional IV Therapy Can Combat Stress & Fatigue", date: "December 18, 2025", image: "/new-blogs-images/how-nutritional-iv-therapy-can-combat-stress-and-fatigue.webp", excerpt: "Learn how personalized nutritional IV therapy in Reno can relieve stress, muscle fatigue, and boost your mental and physical performance.", category: "nutritional-ivs" },
  { slug: "get-rid-of-mid-back-stiffness-after-whiplash-without-surgery", title: "Get Rid of Mid Back Stiffness After Whiplash Without Surgery", date: "December 11, 2025", image: "/new-blogs-images/get-rid-of-mid-back-stiffness-after-whiplash-without-surgery.jpg", excerpt: "Reno Regenerative Medicine provides non-surgical relief for mid-back stiffness after whiplash using chiropractic care and spinal decompression", category: "chiropractic-care" },
  { slug: "that-numbness-in-your-feet-when-walking-could-be-neuropathy", title: "That Numbness in your Feet when Walking Could Be Neuropathy", date: "December 4, 2025", image: "/images/blogs-images/unique-that-numbness-in-your-feet-when-walking-could-be-neuropathy.jpg", excerpt: "If you feel buzzing numbness in your feet when walking, Reno Regenerative Medicine offers effective neuropathy relief with trigger point injections.", category: "trigger-point-injections" },
  { slug: "unlock-your-best-self-how-regenerative-medicine-boosts-hormone-health", title: "Unlock Your Best Self: How Regenerative Medicine Boosts Hormone Health", date: "November 27, 2025", image: "/images/blogs-images/unique-unlock-your-best-self-how-regenerative-medicine-boosts-hormone-health.jpg", excerpt: "Alright, let\u2019s talk about something truly important for feeling your best: your hormones. You see, these powerful little messengers in your body make everything tick", category: "regenerative-medicine" },
  { slug: "heal-and-thrive-the-power-of-regenerative-medicine", title: "Heal and Thrive: The Power of Regenerative Medicine", date: "November 20, 2025", image: "/new-blogs-images/heal-and-thrive-the-power-of-regenerative-medicine.jpg", excerpt: "Do you often feel held back by pain? Maybe your joints ache, your back hurts, or you just don\u2019t feel as strong and healthy as", category: "regenerative-medicine" },
  { slug: "do-you-suffer-from-these-symptoms-of-arthritis", title: "Do You Suffer from These Symptoms of Arthritis?", date: "November 13, 2025", image: "/images/blogs-images/unique-do-you-suffer-from-these-symptoms-of-arthritis.jpg", excerpt: "Arthritis is an umbrella term for about 100 different conditions that affect your joints. If you have arthritis, your joints are under attack. The attack", category: "regenerative-medicine" },
  { slug: "treat-your-sports-injury-with-chiropractic-care", title: "Treat Your Sports Injury with Chiropractic Care", date: "November 6, 2025", image: "/images/blogs-images/unique-treat-your-sports-injury-with-chiropractic-care.jpg", excerpt: "Sports Injury with Chiropractic Care Treating a sports injury with Chiropractic care works with your body to help it heal itself. At Reno Regenerative", category: "chiropractic-care" },
];

export function getPost(slug: string): Post | undefined {
  return POSTS.find((p) => p.slug === slug);
}

export function getRelatedPosts(slug: string, limit = 3): Post[] {
  const current = getPost(slug);
  const others = POSTS.filter((p) => p.slug !== slug);
  if (!current || !current.category) return others.slice(0, limit);
  const sameCat = others.filter((p) => p.category === current.category);
  const fill = others.filter((p) => p.category !== current.category);
  return [...sameCat, ...fill].slice(0, limit);
}
